version: '3.8'

networks:
  main-net:
    driver: bridge

services:
  server:
    image: server:0.0.1
    container_name: main-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8181:8181'
    depends_on:
      - db
    networks:
      - main-net
    links:
      - "db:database"
      - "db:db-server"
    environment:
      - AUTH_SERVER_URL=http://auth-server:8282
      - COOKIE_MAX_AGE=300
  db:
    image: postgres:16.0-alpine
    container_name: server-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=ecommerce_password
      - POSTGRES_DB=ecommerce_db
    volumes:
      - ./infrastructure/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecommerce_user -d ecommerce_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - main-net