version: '3.8'

services:
  web:
    build: apache/.
    restart: always
    volumes:
      - ./apache:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    volumes:
      - ./db:/docker-entrypoint-initdb.d