version: '3.8'

services:
  server:
    image: server:0.0.1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8181:8181'
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=dev_server_app_db
    volumes:
      - ./infrastructure/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_user -d dev_server_app_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
