server:
  port: 8181
spring:
  datasource:
    username: ecommerce_user
    password: ecommerce_password
    url: jdbc:postgresql://db:5432/ecommerce_db
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html
